# === 0. Minimum Requirements ===
brew "coreutils"
brew "bash"
brew "openssl@1.1"
brew "wget"
brew "watch"
brew "rename"
brew "tree"
brew "zsh"
brew "stow"

# === 1. System Libraries / Runtime ===
brew "apr-util"
brew "libevent"
brew "libssh2"
brew "bzip2"
brew "glib"
brew "pcre"
brew "pcre2"
brew "unbound"
brew "gnutls"
brew "rtmpdump"
brew "freetds"
brew "tidy-html5"
brew "libfido2"

# === 2. Casks: GUI Applications ===
cask "blackhole-16ch"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "google-cloud-sdk"
cask "hiddenbar"
cask "jordanbaird-ice"
cask "keycastr"
cask "neardrop"
cask "ngrok"
cask "sip-app"
cask "slack-cli"
cask "thebrowsercompany-dia"
cask "wezterm@nightly"

# === 3. External Taps ===
tap "aquaproj/aqua"
tap "cloudquery/tap"
tap "grishka/grishka"
tap "homebrew/bundle"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "ngrok/ngrok"
tap "owlinux1000/tap"
tap "shopify/shopify"

# === 4. Development Tools ===
brew "gh"
brew "go"
brew "neovim"
brew "lazygit"
brew "starship"
brew "sqlparse"
brew "reattach-to-user-namespace"
brew "perl"
brew "jq"
brew "ripgrep"
brew "fd"
brew "dateutils"
brew "pycparser"
brew "cffi"
brew "cryptography"
brew "docutils"
brew "pwgen"
brew "tfenv"
brew "fzf"
brew "tmux"
brew "blueutil"
brew "nkf"
brew "pngpaste"
brew "osv-scanner"
brew "openfortivpn"
brew "php"
brew "composer"
brew "pyenv"
brew "pyenv-virtualenv"
brew "python-yq", link: false
brew "python@3.9"
brew "python@3.10"
brew "python@3.11"
brew "python@3.12"

# === 5. Package Managers ===
brew "nvm"
brew "volta"
brew "aquaproj/aqua/aqua"
brew "fnm"

# === 6. Cloud / Infra Tools ===
brew "awscli"
brew "argo"
brew "cloudquery/tap/cloudquery"
brew "owlinux1000/tap/gcstree"
brew "shopify/shopify/shopify-cli"
brew "mysql", restart_service: :changed
brew "mysql-client"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"

# === 7. Visual / CLI Utility ===
brew "bat"
brew "xq"
brew "yq"
brew "cmatrix"
brew "parallel"
brew "gdrive"

# === 8. Media / Graphics ===
brew "aom"
brew "libavif"
brew "jpeg-xl"
brew "jpegoptim"
brew "webp"
brew "little-cms2"
brew "openjpeg"
brew "leptonica"
brew "libheif"
brew "libraw"
brew "gd"
brew "gdk-pixbuf"
brew "graphviz"
brew "netpbm"
brew "ghostscript"
brew "imagemagick"
brew "pango"
brew "harfbuzz"
brew "tesseract"
brew "yt-dlp"
brew "ffmpeg"
brew "librsvg"
